export const mitgliedSprach = [
    {
        "logout": "Log-Out",
        "projektAmount": "Project",
        "contractAmount": "Discussion",
        "personalInformation": "Information",
        "hinzufugenProjekt": "Create a Project",
        "projektNumer": "Project Number",
        "projektTitel": "Project Title",
        "erstelltZeit": "Created Time",
        "hinzufugenVertrag": "Generate new Discussion",
        "vertragNumer": "Discussion Number",
        "erstelltBei": "Created by",
        "vertragName": "Discussion Title",
        "vertragstatus": "Status",
        "letzteUpdaten": "Last Update",
        "updatenBei": "Updated by",
        "dreitenParteiVertrag": "Witness Discusstion",
        "berufNumer": "Occupation Number",
        "email": "Email",
        "ort": "Location",
        "phone": "Phone",
        "sprach": "Language",
        "website": "Website",
        "social": "Social",
        "firm": "Firm",
        "intro": "Intro",
        "experience": "Experience",
        "education": "Education",
        "quotation": "Quotation"
    },
    {
        "logout": "登出",
        "projektAmount": "專案",
        "contractAmount": "討論",
        "personalInformation": "個人資料",
        "hinzufugenProjekt": "創立專案",
        "projektNumer": "專案編號",
        "projektTitel": "專案名稱",
        "erstelltZeit": "創立時間",
        "hinzufugenVertrag": "新討論",
        "vertragNumer": "編號",
        "erstelltBei": "創立者",
        "vertragName": "名稱",
        "vertragstatus": "狀態",
        "letzteUpdaten": "更新時間",
        "updatenBei": "更新者",
        "dreitenParteiVertrag": "第三人",
        "berufNumer": "職業編號",
        "email": "信箱",
        "ort": "位置",
        "phone": "電話",
        "sprach": "語言",
        "website": "網站",
        "social": "社群",
        "firm": "公司",
        "intro": "簡介",
        "experience": "經歷",
        "education": "教育",
        "quotation": "服務費用"
    },
    {
        "logout": "登出",
        "projektAmount": "專案",
        "contractAmount": "讨论",
        "personalInformation": "个人信息",
        "hinzufugenProjekt": "创立专案",
        "projektNumer": "专案编号",
        "projektTitel": "专案名称",
        "erstelltZeit": "创立时间",
        "hinzufugenVertrag": "新讨论",
        "vertragNumer": "编号",
        "erstelltBei": "创立者",
        "vertragName": "名称",
        "vertragstatus": "状态",
        "letzteUpdaten": "更新时间",
        "updatenBei": "更新者",
        "dreitenParteiVertrag": "第三人",
        "berufNumer": "职业编号",
        "email": "电邮",
        "ort": "位置",
        "phone": "电话",
        "sprach": "语言",
        "website": "网站",
        "social": "社群",
        "firm": "公司",
        "intro": "简介",
        "experience": "经历",
        "education": "教育",
        "quotation": "服务费用"
    },
    {
        "logout": "Wyloguj",
        "projektAmount": "Projekt",
        "contractAmount": "Dyskusja",
        "personalInformation": "Informacja",
        "hinzufugenProjekt": "Utwórz Projekt",
        "projektNumer": "Numer Projektu",
        "projektTitel": "Tytuł Projektu",
        "erstelltZeit": "Utworzono Czas",
        "hinzufugenVertrag": "Wygeneruj nowy Dyskusja",
        "vertragNumer": "Numer Dyskusja",
        "erstelltBei": "Stworzone Przez",
        "vertragName": "Tytuł Dyskusji",
        "vertragstatus": "Status",
        "letzteUpdaten": "Ostatnia aktualizacja",
        "updatenBei": "Aktualizowany Przez",
        "dreitenParteiVertrag": "Dyskusja świadka",
        "berufNumer": "Numer zawodu",
        "email": "Email",
        "ort": "Lokalizacja",
        "phone": "Phone",
        "sprach": "Język",
        "website": "Website",
        "social": "Społeczny",
        "firm": "solidny",
        "intro": "Wstęp",
        "experience": "Doświadczenie",
        "education": "Edukacja",
        "quotation": "Cytat"
    },
]

export default mitgliedSprach; 