export const mitgliedEditSprache = [
    {
        "kontoNumer": "Account Number",
        "kontoName": "Account Name",
        "ändernPasswort": "Change Password",
        "gleich": "Match",
        "geprüftStatus": "Verified Status",
        "geprüft": "Verified",
        "gelten": "Apply",
        "verzugSprache": "Default Language",
        "offiziellName": "Official Name",
        "email": "E-Mail",
        "phone": "Phone",
        "standOrt": "Location",
        "spracheSprechen": "Language",
        "firmWerk": "Company",
        "besetzung": "Occupation",
        "aufSpezialisieren": "Specialize in",
        "kontoTitel": "Personal Title",
        "website": "Website",
        "sozialeNetzwerke": "Social Media",
        "anschreiben": "Brief",
        "erfahrung": "Experience",
        "ausbildung": "Education",
        "angebot": "Quotation",
        "updateButton": "Update"
    },
    {
        "kontoNumer": "帳號號碼",
        "kontoName": "帳號名稱",
        "ändernPasswort": "更改密碼",
        "gleich": "相同",
        "geprüftStatus": "審核",
        "geprüft": "通過審核",
        "gelten": "申請",
        "verzugSprache": "預設語言",
        "offiziellName": "姓名",
        "email": "電子郵箱",
        "phone": "電話",
        "standOrt": "所在地",
        "spracheSprechen": "擅長語言",
        "firmWerk": "所在公司",
        "besetzung": "職業",
        "aufSpezialisieren": "專長",
        "kontoTitel": "個人別稱",
        "website": "網站",
        "sozialeNetzwerke": "社群媒體",
        "anschreiben": "自我簡述",
        "erfahrung": "經歷",
        "ausbildung": "教育",
        "angebot": "報價",
        "updateButton": "更新"
    },
    {
        "kontoNumer": "帐号号码",
        "kontoName": "帐号名称",
        "ändernPasswort": "更改密码",
        "gleich": "相同",
        "geprüftStatus": "审核",
        "geprüft": "通过审核",
        "gelten": "申请",
        "verzugSprache": "预设语言",
        "offiziellName": "姓名",
        "email": "电邮",
        "phone": "电話",
        "standOrt": "所在地",
        "spracheSprechen": "擅长语言",
        "firmWerk": "所在公司",
        "besetzung": "职业",
        "aufSpezialisieren": "专长",
        "kontoTitel": "个人别称",
        "website": "网站",
        "sozialeNetzwerke": "社群媒体",
        "anschreiben": "简述",
        "erfahrung": "经历",
        "ausbildung": "教育",
        "angebot": "报价",
        "updateButton": "更新"
    },
    {
        "kontoNumer": "Numer Konta",
        "kontoName": "Konta",
        "ändernPasswort": "Zmień Hasło",
        "gleich": "Match",
        "geprüftStatus": "Status Zweryfikowany",
        "geprüft": "Zweryfikowany",
        "gelten": "Zastosować",
        "verzugSprache": "Domyślny język",
        "offiziellName": "Oficjalne Imię",
        "email": "E-Mail",
        "phone": "Telefon",
        "standOrt": "Lokalizacja",
        "spracheSprechen": "Język",
        "firmWerk": "Spółka",
        "besetzung": "Zawód",
        "aufSpezialisieren": "Specializować Się w",
        "kontoTitel": "Tytuł",
        "website": "Website",
        "sozialeNetzwerke": "Media Społecznościowe",
        "anschreiben": "Własne Krótkie",
        "erfahrung": "Doświadczenie",
        "ausbildung": "Edukacja",
        "angebot": "Cytat",
        "updateButton": "Aktualizacja"
    },
]

//export default { oemVertrag }
export default mitgliedEditSprache; 