export const vertragSprche = [
    {
        "zeigenDetail": "Show detail",
        "versteckenDetail": "Hide detail",
        "vertragErfolgt": "This Discussion is made by",
        "und": "and",
        "vertragErfolgtMit": "You can make Discussion with",
        "suche": "Search",
        "einladungscode": "Invitation Code",
        "alertEinladungscodeEinzeugen": "You want to cancel invitation Code auto-generated?",
        "bestätigenEinladungscodeEinzeugen": "Invitation Code is auto-generated",
        "serieNumer": "Serial Number",
        "schaffenZeit": "Created Time",
        "aktuellZeit": "Current Status",
        "LetzteUpdaten": "Last Update",
        "vertragName": "Discussion Name",
        "hinzufügenVertragName": "Click to add a Name",
        "ändern": "Change",
        "status": "Status",
        "private": "PRIVATE",
        "public": "PUBLIC",
        "privateAlert": "Are you sure you want to switch the Discussion status to Public?",
        "publicAlert": "Are you sure you want to switch the Discussion status to Private?",
        "updateAlert": "press to update",
        "projekt": "Project",
        "keinProjekt": "Link no Project",
        "hinzufugen": "Add",
        "verbindenProjekt": "Click to link a Project",
        "dreitePartei": "3rd Party",
        "keineDreitePartei": "no 3rd Party appointed",
        "point": "Appoint",
        "hinzufugenVertrag": "Create",
        "sendVertrag": "Send",
        "updatenVertrag": "Update",
        "consentVertrag": "Agree",
        "deleteVertrag": "Delete",
        "certifyVertrag": "Certify",
        "enterProjektNumer": "Enter the Project Number",
        "enterOccupationNumer": "Enter Occupation Number"
    },
    {
        "zeigenDetail": "展開",
        "versteckenDetail": "隱藏",
        "vertragErfolgt": "這個討論是關於",
        "und": "以及",
        "vertragErfolgtMit": "討論一方為",
        "suche": "尋找",
        "einladungscode": "邀請碼",
        "alertEinladungscodeEinzeugen": "取消邀請碼自動產生功能?",
        "bestätigenEinladungscodeEinzeugen": "邀請碼將會自動產生",
        "serieNumer": "序號",
        "schaffenZeit": "創立時間",
        "aktuellZeit": "目前狀態",
        "LetzteUpdaten": "最後更新",
        "vertragName": "名稱",
        "hinzufügenVertragName": "新增名稱",
        "ändern": "確認",
        "status": "狀態",
        "private": "不公開",
        "public": "公開",
        "privateAlert": "你確定要轉換成公開狀態?",
        "publicAlert": "你確定要轉換成不公開狀態?",
        "updateAlert": "請更新",
        "projekt": "專案",
        "keinProjekt": "無專案連結",
        "hinzufugen": "新增",
        "verbindenProjekt": "連結一專案",
        "dreitePartei": "第三方",
        "keineDreitePartei": "未指定第三方",
        "point": "指定",
        "hinzufugenVertrag": "創立",
        "sendVertrag": "傳送",
        "updatenVertrag": "更新",
        "consentVertrag": "同意",
        "deleteVertrag": "刪除",
        "certifyVertrag": "見證",
        "enterProjektNumer": "輸入專案號碼",
        "enterOccupationNumer": "輸入職業號碼"
    },
    {
        "zeigenDetail": "展开",
        "versteckenDetail": "隐藏",
        "vertragErfolgt": "这个讨论是关于",
        "und": "以及",
        "vertragErfolgtMit": "讨论一方为",
        "suche": "寻找",
        "einladungscode": "邀请码",
        "alertEinladungscodeEinzeugen": "取消邀请码自动产生功能?",
        "bestätigenEinladungscodeEinzeugen": "邀请码将会自动产生",
        "serieNumer": "序号",
        "schaffenZeit": "创立时间",
        "aktuellZeit": "目前状态",
        "LetzteUpdaten": "最后更新",
        "vertragName": "名称",
        "hinzufügenVertragName": "新增名称",
        "ändern": "确认",
        "status": "状态",
        "private": "不公开",
        "public": "公开",
        "privateAlert": "你确定要转换成公开状态?",
        "publicAlert": "你确定要转换成不公开状态?",
        "updateAlert": "请更新",
        "projekt": "专案",
        "keinProjekt": "无专案连结",
        "hinzufugen": "新增",
        "verbindenProjekt": "连结一专案",
        "dreitePartei": "第三方",
        "keineDreitePartei": "未指定第三方",
        "point": "指定",
        "hinzufugenVertrag": "创立",
        "sendVertrag": "传送",
        "updatenVertrag": "更新",
        "consentVertrag": "同意",
        "deleteVertrag": "刪除",
        "certifyVertrag": "见证",
        "enterProjektNumer": "输入专案号码",
        "enterOccupationNumer": "输入职业号码"
    },
    {
        "zeigenDetail": "Pokaż Szczegół",
        "versteckenDetail": "Ukryj Szczegóły",
        "vertragErfolgt": "Ta dyskusja została wykonana przez",
        "und": "oraz",
        "vertragErfolgtMit": "Możesz przeprowadzić dyskusję z",
        "suche": "Szukaj",
        "einladungscode": "Kod zaproszenia",
        "alertEinladungscodeEinzeugen": "Chcesz anulować zaproszenie Kod wygenerowany automatycznie?",
        "bestätigenEinladungscodeEinzeugen": "Kod zaproszenia jest generowany automatycznie",
        "serieNumer": "Numer seryjny",
        "schaffenZeit": "Utworzono czas",
        "aktuellZeit": "Aktualny stan",
        "LetzteUpdaten": "Ostatnia aktualizacja",
        "vertragName": "Nazwa Dyskusja",
        "hinzufügenVertragName": "Kliknij, aby dodać nazwę",
        "ändern": "Reszta",
        "status": "Status",
        "private": "PRYWATNY",
        "public": "PUBLICZNY",
        "privateAlert": "Czy na pewno chcesz zmienić status dyskusji na Publiczna?",
        "publicAlert": "Czy na pewno chcesz zmienić status dyskusji na Prywatny??",
        "updateAlert": "naciśnij, aby zaktualizować",
        "projekt": "Projekt",
        "keinProjekt": "Link bez projektu",
        "hinzufugen": "Dodać",
        "verbindenProjekt": "Kliknij, aby połączyć projekt",
        "dreitePartei": "Strona trzecia",
        "keineDreitePartei": "nie wyznaczono trzeciej strony",
        "point": "wyznaczać",
        "hinzufugenVertrag": "Tworzyć",
        "sendVertrag": "Wysłać",
        "updatenVertrag": "Aktualizacja",
        "consentVertrag": "Zgadzać się",
        "deleteVertrag": "Kasować",
        "certifyVertrag": "Poświadczać",
        "enterProjektNumer": "Wprowadź numer projektu",
        "enterOccupationNumer": "Wpisz numer zawodu"
    },
]

export default vertragSprche; 